fix(managedcache): synthesize an unstructured object  and call cache.GetInformer instead of cache.GetInformerForKind to avoid a scheme lookup error
Error: object /a-foo kind:Foo: getting k8s.erdii.net/v1, Kind=Foo: no kind \"Foo\" is registered for version \"k8s.erdii.net/v1\" in scheme \"pkg/runtime/scheme.go:100\"

we're using controller-runtime's informerCache [1] and that implementation's GetInformerForKind tries to instanciate a new typed struct for the given gvk [2]. This does not work because the scheme does not contain the type.

[1] https://github.com/kubernetes-sigs/controller-runtime/blob/6ad5c1dd4418489606d19dfb87bf38905b440561/pkg/cache/informer_cache.go#L67
[2] https://github.com/kubernetes-sigs/controller-runtime/blob/6ad5c1dd4418489606d19dfb87bf38905b440561/pkg/cache/informer_cache.go#L155